<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:core="http://www.omg.org/spec/CTS2/1.3/Core"
	xmlns:coreService="http://www.omg.org/spec/CTS2/1.3/CoreService"
	xmlns="http://www.omg.org/spec/CTS2/1.3/Exceptions"
	targetNamespace="http://www.omg.org/spec/CTS2/1.3/Exceptions"
	elementFormDefault="qualified">
	<xs:import namespace="http://www.omg.org/spec/CTS2/1.3/Core" schemaLocation="../core/Core.xsd" />
	<xs:import namespace="http://www.omg.org/spec/CTS2/1.3/CoreService" schemaLocation="../core/CoreService.xsd" />

	<xs:element name="CTS2Exception" type="CTS2Exception" />
	<xs:complexType name="CTS2Exception" abstract="true">
		<xs:annotation>
			<xs:documentation>An exception generated by the CTS 2 service.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="message" type="core:OpaqueData"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="severity" type="coreService:LoggingLevel"
				minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

	<!-- Exception Model (Core/InterfaceElements/InterfaceElementExceptions) -->
	<xs:element name="UnknownValueSet">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The value set name or URI is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownCodeSystemVersion">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The referenced CodeSystemVersion is not recognized
					by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownResourceReference" type="UnknownResourceReference" />
	<xs:complexType name="UnknownResourceReference">
		<xs:annotation>
			<xs:documentation>A $CTS_2$ resource was referenced by name, URI or
				external identifier that was not known to the $CTS_2$ service
				instance. </xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="CTS2Exception">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="UnknownEntity" type="UnknownEntity" />
	<xs:complexType name="UnknownEntity">
		<xs:annotation>
			<xs:documentation>The EntityNameOrURI is not known to the service
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="UnknownResourceReference">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="UnknownCodeSystem">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The referenced CodeSystem is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="UnknownStatement">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The referenced statement is not recognized by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownChangeSet">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The change set specified could either not be read
					or located by the service.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownAssociation">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The referenced Association is not recognized by
					the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownConceptDomain">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The named conceptDomain is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownConceptDomainBinding">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The conceptDomainBinding URI is not recognized by
					the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownMap">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The named Map is not recognized by the service
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownMapVersion">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The named mapVersion is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownValueSetDefinition">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The valueSetDefinition URI isn't recognized by the
					service.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownResourceReference">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedBindingQualifier">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The bindingQualifier is not recognized by the
					system.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedStatus">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The name or URI of the Changeable status property
					is not recognized by the service.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedRole">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The role name or URI is not recognized by the
					service.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedNamespaceName" type="UnsupportedNamespaceName" />
	<xs:complexType name="UnsupportedNamespaceName">
		<xs:annotation>
			<xs:documentation>The supplied namespace name is not one that is
				known to the service.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="CTS2Exception">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="UnsupportedLanguage">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The referenceLanguage is not supported by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedContext">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>One or more changeSetContext is not supported by
					the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedNameOrURI" type="UnsupportedNameOrURI" />
	<xs:complexType name="UnsupportedNameOrURI">
		<xs:annotation>
			<xs:documentation>The supplied NameOrURI is not recognized by the
				service.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="CTS2Exception">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="UnsupportedVersionTag">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The versionTag is not recognized by the service
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedMatchAlgorithm">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The matchAlgorithm is not supported by the service
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="MatchValueFormatException">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The match value does not meet the format or syntax required or the supplied match algorithm.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedOntologyLanguage">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied ontology language is not supported by
					the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedOntologySyntax">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied ontology syntax is not supported by
					the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedSource">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied source is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedCaseSignificance">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The caseSignificance indicator is not recognized
					by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedDesignationFidelity">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The designationFidelity is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedDesignationType">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The designationType is not supported by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedFormat">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The format is not supported by the service
					implementation</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedFormalityLevel">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The formalityLevel is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedMapCorrelation">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The mapCorrelation is not recognized by the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedModelAttribute">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The name or URI of $CTS_2$ model attribute is not
					recognized and/or supported by the service implementation
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedOntologyEngineeringMethodology">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The name or URI for the
					OntologyEngineeringMethodology is not recognized by the service.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedOntologyEngineeringTool">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The name or URI for the OntologyEngineeringTool is
					not recognized by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedOntologyDomain">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The name or URI for the OntologyDomain is not
					recognized by the service.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedOntologyTask">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The name or URI for the OntologyTask is not
					recognized by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedOntologyType">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The name or URI for the OntologyType is not
					recognized by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNameOrURI">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedPredicate" type="UnsupportedPredicate" />
	<xs:complexType name="UnsupportedPredicate">
		<xs:annotation>
			<xs:documentation>The predicate name or URI is not recognized by the
				service</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="UnsupportedNameOrURI">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="EntityExpressionSyntaxError">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The entity expression is syntactically incorrect
					and cannot be parsed</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ChangeSetIsNotOpen">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The changeSetContext is recognized but the
					service, but it state is not OPEN.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End Exception Model (Core/InterfaceElements/InterfaceElementExceptions) -->

	<!-- Exception Model (Core/FunctionalProfiles/Maintenance/ResourceMaintenance/ResourceMaintenanceExceptions) -->
	<xs:element name="ResourceURIAlreadyExists">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The URI (entityID) of the supplied resource
					already exists in the service.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="AlternateURINotUnique">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>One of the supplied alternateIDs is not unique - it appears as an entryID or alternateID for a different resource of the same type.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="UnknownEntryID">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The Changeable resource referenced by entryID is not recognized by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="WrongPredecessorType">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The predecessor URI is not of the same type as its
					successor.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ResourceNameAlreadyExists" type="ResourceNameAlreadyExists" />
	<xs:complexType name="ResourceNameAlreadyExists">
		<xs:annotation>
			<xs:documentation>The local identifier for the resource already
				exists in the service.</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="CTS2Exception">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="CycleInPredecessor">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The predecessor resource directly or indirectly
					precedes the resource being updated.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ResourceIsNotOpen">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The target resource version description has been
					finalized and cannot be updated.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ResourceStateMismatch">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The resource being deleted did not match the state
					of the resource in the service. A change has occurred since the
					resource image has been retrieved.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<!--End Exception Model (Core/FunctionalProfiles/Maintenance/ResourceMaintenance/ResourceMaintenanceExceptions) -->

	<!-- Exception Model (Core/FunctionalProfiles/Query/QueryExceptions) -->
	<xs:element name="InvalidDirectoryType">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The type represented by the supplied directory URI
					is not the one required by the service invocation.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedPropertyReferenceTarget">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The set of exceptions that pertain to a
					PropertyReferenceTarget</xs:documentation>
			</xs:annotation>
			<xs:sequence />
		</xs:complexType>
	</xs:element>

	<xs:element name="QueryTimeout">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The timeLimit was exceeded by the service.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="InvalidDirectoryURI">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied directory URI is not valid
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<!-- End Exception Model (Core/FunctionalProfiles/Query/QueryExceptions) -->


	<!-- Start EntityDescription Exceptions -->
	<xs:element name="EntityIDMustBeSupplied">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The service requires that the scoped entity name
					be provided</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="EntityIDMustBeGeneratedByService">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The service expects to automatically generate the
					entityID for the supplied code system. It cannot be supplied in the
					API call.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="EntityAlreadyExists">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>A description of the named entity already exists
					in the code system version</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End EntityDescription Exceptions -->


	<!-- Start CodeSystemVersion Exceptions -->
	<xs:element name="DuplicateCodeSystemVersionURI">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied code system version URI is already a
					documentURI or alternateID for an existing code system version.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="DuplicateCodeSystemVersionName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied code system version name is already
					used for another entry.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End CodeSystemVersion Exceptions -->


	<!-- Start Association Exceptions -->
	<xs:element name="UnsupportedSubjectNamespaceName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The namespace in the subject identifier is not
					known to or supported by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNamespaceName">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedAssociationQualifier">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The predicate of an association qualifier is not
					recognized by the service or is not considered to be a valid
					association qualifier.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedPredicate">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownTargetEntity">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The target EntityNameOrURI is not known to the
					service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownEntity">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownAssociationQualifierNamespaceName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The namespace in the predicate identifier is not
					known to or supported by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownPredicateNamespaceName">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="AssociationAlreadyExists">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The service has determined that an association
					with the same identity criteria as the supplied association already
					exists in the service. What constitutes identity from an
					association standpoint is up to the service implementation.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="UnknownFocusEntity">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownPredicateNamespaceName" type="UnknownPredicateNamespaceName" />
	<xs:complexType name="UnknownPredicateNamespaceName">
		<xs:annotation>
			<xs:documentation>The namespace in the predicate identifier is not
				known to or supported by the service</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="UnsupportedNamespaceName">
				<xs:sequence />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="UnknownSubjectEntity">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The EntityNameOrURI is not known to the service
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnknownEntity">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnknownTargetNamespaceName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The namespace in a target entity identifier is not
					known to or supported by the service</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="UnsupportedNamespaceName">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End Association Exceptions -->


	<!-- Start MapCatalog Exceptions -->
	<xs:element name="MapCatalogToReferenceException">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Exactly one of toCodeSystem and toValueSet must be
					supplied in a map catalog entry</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="MapCatalogFromReferenceException">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Exactly one of fromCodeSystem and fromValueSet
					must be supplied in a map catalog entry</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="DuplicateMapName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied mapName already exists in the service
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End MapCatalog Exceptions -->


	<!-- Start MapVersion Exceptions -->
	<xs:element name="MapVersionToReferenceException">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Exactly one of toCodeSystemVersion and
					toValueSetDefinition must be supplied in a map version
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="MapVersionFromReferenceException">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Exactly one of fromCodeSystemVersion and
					fromValueSetDefinition must be supplied in a map version
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="DuplicateMapVersionName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The mapVersionName already exists in the catalog.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="ResourceNameAlreadyExists">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End MapVersion Exceptions -->


	<!-- Start ConceptDomainCatalog Exceptions -->
	<xs:element name="DuplicateDefiningEntity">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>More than one concept domain is defined by the
					same definingEntity.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="NoCatalogEntryForDefiningEntity">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>There isn't any catalog entry that references the
					supplied entity in the supplied context.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="DuplicateConceptDomainURI">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied URI is already the about URI or
					alternateID for another concept domain in the service.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="DuplicateConceptDomainName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The concept domain name is already used for
					another catalog entry</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End ConceptDomainCatalog Exceptions -->


	<!-- Start ValueSetCatalog Exceptions -->
	<xs:element name="DuplicateValueSetURI">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied value set URI already exists as an
					about or alternateID for a value set in the service.
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="DuplicateValueSetName">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied valueSetName already exists in the
					service.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End ValueSetCatalog Exceptions -->


	<!-- Start ValueSetDefinition Exceptions -->
	<xs:element name="InvalidIndexNumber">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied number does not reference an existing
					ValueSetDefinitionEntry or the operation would remove the last
					ValueSetDefinitionEntry from a definition.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ValueSetDefinitionMismatch">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The named value set definition was not a
					definition for the named value set.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="CodeSystemVersionMismatch">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The named code system version is not a version of
					the named code system.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End ValueSetDefinition Exceptions -->

	<!-- Reasoning Exceptions -->
	<xs:element name="InferenceNotSupported">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Inference is not supported for the supplied
					codeSystemVersion</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- Reasoning Exceptions -->

	<!-- ImportExportExceptions -->
	<xs:element name="ResourceAlreadyExists">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>a referenced resource already exists and overWrite
					is set to FAIL_IF_EXISTS</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="UnknownProcessId">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The processId is not known to the service
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="UnableToOpenDocument">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>the process is unable to open the primary document
					to be imported</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="ResourceWriteError">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>an error occurred while trying to write the
					exported image of a resource into the directory</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnsupportedResourceType">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>the type of resource referenced by the directory
					is not supported by the service - either it can't be exported
					period or it can't be exported in the supplied language or format
				</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnableToOpenMetadataDocument">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>the service is unable to access the supplied
					metadata document</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="MetadataError">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>An error was encountered in the metadata document.
					This error includes formatting errors, missing parameters and
					invalid content.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="UnableToOpenOrCreateTargetDirectory">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>the export service is unable to open or create the
					supplied target directory</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="MetadataDocumentRequired">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>Additional metadata must be supplied to perform
					this operation</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence />
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<!-- ImportExportExceptions -->
	
	<!-- MapEntry Exceptions -->
	<xs:element name="ToEntityNotValid">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The mapTo entity is not part of the toCodeSystemVersion or toValueSet in the map</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="IllegalEntryOrder">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The entryOrder does not reference an existing MapEntry</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="FromEntityNotValid">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied mapFrom entry is not a valid entity in the containing map's fromCodeSystem or fromValueSet.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="InvalidMapRule">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied map rule is not recognized by the supporting tooling</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="CannotDeleteOnlyTarget">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>A  MapSet must have at least one map target.  The last target cannot be removed from the set</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="DuplicateMapEntry">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The mapFrom entity already exists</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="FromEntryNotInMap">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The supplied fromEntry is not associated with any MapEntry in the referenced MapVersion.</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="IllegalTargetSlot">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>The referenced target slot is not valid in the containing map set</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<!-- End MapEntry Exceptions -->
	
	<!-- ValueSetDefinitionResolution Exceptions -->
	<xs:element name="UnrecognizedResolvedValueSet">
		<xs:complexType>
			<xs:annotation>
				<xs:documentation>the LocalURI is not the name of a valid resolved value set</xs:documentation>
			</xs:annotation>
			<xs:complexContent>
				<xs:extension base="CTS2Exception">
					<xs:sequence/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<!-- End ValueSetDefinitionResolution Exceptions -->
</xs:schema>
